export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const ADD_ELEMENT = 'ADD_ELEMENT'
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT'
export const RESIZE_ELEMENT = 'RESIZE_ELEMENT'
export const MOVE_ELEMENT = 'MOVE_ELEMENT'

export const ADD_PAGE = 'ADD_PAGE'
export const REMOVE_PAGE = 'REMOVE_PAGE'
export const CHANGE_PAGE_PATH = 'CHANGE_PAGE_PATH'

const types = {
  TOGGLE_SIDEBAR,
  ADD_ELEMENT,
  REMOVE_ELEMENT,
  RESIZE_ELEMENT,
  MOVE_ELEMENT,
  ADD_PAGE,
  REMOVE_PAGE,
  CHANGE_PAGE_PATH
}

export default types
